### ISSUE TITLE
Data structure needs for the CLI (tracking issue)

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#37]
Creating an issue to track fields / features I need from the data store to implement the CLI.

- Post
  - [ ] ID
  - [ ] Created-at timestamp
  - [ ] All fields related to post replies
  - [ ] Edit(), delete()
- Social
  - [ ] A way to query followers
  - [ ] Unfollow()
- Interactions
  - [ ] Everything
